# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cg < Formula
  desc "CoinGecko CLI — cryptocurrency data at your fingertips"
  homepage "https://github.com/coingecko/coingecko-cli"
  version "1.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coingecko/coingecko-cli/releases/download/v1.0.10/cg_1.0.10_darwin_amd64.tar.gz"
      sha256 "4bca714a1fc0176d06b939cf5395794ac5a62c0bdc8060764e42d544bd89916d"

      define_method(:install) do
        bin.install "cg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coingecko/coingecko-cli/releases/download/v1.0.10/cg_1.0.10_darwin_arm64.tar.gz"
      sha256 "1f792182d2a8b017b0230bc4e9cbbe864c3068483da4a21a67f0c324c750dd61"

      define_method(:install) do
        bin.install "cg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coingecko/coingecko-cli/releases/download/v1.0.10/cg_1.0.10_linux_amd64.tar.gz"
      sha256 "53114258d6c32bdd023091315b3131f7c8ad228bede6d9f365a1c6761d04fdba"
      define_method(:install) do
        bin.install "cg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coingecko/coingecko-cli/releases/download/v1.0.10/cg_1.0.10_linux_arm64.tar.gz"
      sha256 "792951bb251921477ca2af105ffd47f2eb25868cf592c63fdceafd70960b6ea4"
      define_method(:install) do
        bin.install "cg"
      end
    end
  end

  test do
    system "#{bin}/cg", "version"
  end
end
