# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cg < Formula
  desc "CoinGecko CLI — cryptocurrency data at your fingertips"
  homepage "https://github.com/coingecko/coingecko-cli"
  version "1.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coingecko/coingecko-cli/releases/download/v1.1.5/cg_1.1.5_darwin_amd64.tar.gz"
      sha256 "c05c3a94f69b33f8ddf06a92705d4e983bafafe3f15168d82420f7ca926a71ec"

      define_method(:install) do
        bin.install "cg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coingecko/coingecko-cli/releases/download/v1.1.5/cg_1.1.5_darwin_arm64.tar.gz"
      sha256 "4faa8a962dd9eb875479752f3d4f4a7d76ee4f0c44816f8da233adade70f77fa"

      define_method(:install) do
        bin.install "cg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coingecko/coingecko-cli/releases/download/v1.1.5/cg_1.1.5_linux_amd64.tar.gz"
      sha256 "673b06a2718db8cdc7c32e56c53ec80e35e86f44971542ad9bf5c4794448ec05"
      define_method(:install) do
        bin.install "cg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coingecko/coingecko-cli/releases/download/v1.1.5/cg_1.1.5_linux_arm64.tar.gz"
      sha256 "e6141953edcdbd59d2dec1c9b7c36382e8fe54f062aedbea9e87589052afaab9"
      define_method(:install) do
        bin.install "cg"
      end
    end
  end

  test do
    system "#{bin}/cg", "version"
  end
end
