# This file was generated by GoReleaser. DO NOT EDIT.
cask "cg" do
  name "cg"
  desc "CoinGecko CLI — cryptocurrency data at your fingertips"
  homepage "https://github.com/coingecko/coingecko-cli"
  version "1.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cg"

  on_macos do
    on_intel do
      url "https://github.com/coingecko/coingecko-cli/releases/download/v#{version}/cg_#{version}_darwin_amd64.tar.gz"
      sha256 "3076dd73bdaf148bb7eb14a56926bd40f959ccf5020d100ac163139b34b5e10d"
    end
    on_arm do
      url "https://github.com/coingecko/coingecko-cli/releases/download/v#{version}/cg_#{version}_darwin_arm64.tar.gz"
      sha256 "419c6268aa847f5adfbfce2496de78ea374ac628db7e55610b9cf59a4f96ecd0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/coingecko/coingecko-cli/releases/download/v#{version}/cg_#{version}_linux_amd64.tar.gz"
      sha256 "d092f613076a6c4f96b3659285db837bcb60eb492faab75b4f16b506613fb5cc"
    end
    on_arm do
      url "https://github.com/coingecko/coingecko-cli/releases/download/v#{version}/cg_#{version}_linux_arm64.tar.gz"
      sha256 "0b694ddb5428dde5b01b2e407a1dbbd84006fd9f56036544d44eea6938da6279"
    end
  end

  # No zap stanza required
end
